# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SizyApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SizyApp
  pod 'Then'
  pod 'naveridlogin-sdk-ios'
  pod 'Alamofire', '4.7.3'
  # 전체 추가
  pod 'RxKakaoSDK', '~> 2.0.0-beta.3'
  
  target 'SizyAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SizyAppUITests' do
    # Pods for testing
  end

end
